
name: PR Pre-Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  validate-submission:
    name: Validate student submission
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps (none required)
        run: python -V

      - name: Run validation
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python .github/scripts/validate_submission.py
